### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by mizzcode** [hendraaagil/website#50]
mau tanya bang logo edit nya dimana ya?
<img width="647" alt="image" src="https://github.com/hendraaagil/website/assets/101040281/2097567b-bb91-4d3b-bba1-a0549cbae4a0">

**Comment by mizzcode** [comment]
atau hapus logo nya di file apa?

**Comment by hendraaagil** [comment]
pake url
https://github.com/hendraaagil/website/blob/main/src/modules/home/Hero.tsx#L18

**Comment by mizzcode** [comment]
contoh url nya kayak gimana ya bang?

**Comment by hendraaagil** [comment]
iya langsung, contoh url: https://ik.imagekit.io/hendraaagil/assets/blog/pengalaman-menggunakan-prisma-orm/prisma-landing-page.png

**Comment by mizzcode** [comment]
ok makasih mas. kalau cara hosting nya ini tinggal yarn build kah mas?

**Comment by hendraaagil** [comment]
tergantung hosting di mana

**Comment by mizzcode** [comment]
maaf bang banyak tanya hehe, ini kan giscus nya masih terhubung sama giscus bang hendra, edit nya dmna ya bang?

**Comment by hendraaagil** [comment]
https://github.com/hendraaagil/website/blob/main/src/modules/blog/Comment.tsx#L9-L12
